name: Build Windows 2022 with Packer
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: "self-hosted"  # (optional) name of the runner labels, groups
    steps:
      - name: Checkout code
        uses: actions/checkout@main
        
      - name: Load secrets
        uses: 1password/load-secrets-action/configure@v1
        with:
          connect-host: OP_CONNECT_HOST
          connect-token: ${{ secrets.OP_CONNECT_TOKEN }}