name: Build Windows 2022 with Packer
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: "self-hosted"  # (optional) name of the runner labels, groups
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Configure 1Password Service Account
        uses: 1password/load-secrets-action/configure@v1
        with:
          # Persist the 1Password Service Account Authorization token
          # for next steps.
          # Keep in mind that every single step in the job is now
          # able to access the token.
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

         
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: latest
  
      - name: Run `packer init`
        id: init
        run: "packer init ./build.pkr.hcl"

      - name: Load Packer Credentials
        id: load-packer-credentials
        uses: 1password/load-secrets-action@v1
        with:
          export-env: True
        env:
          winrm_password: op://secrets/ProxmoxAPI/winrm_password
  
      - name: Run `packer validate`
        id: validate
        run: "packer validate -var-file=./build.pkrvars.hcl ./build.pkr.hcl"
        env:
          PKR_VAR_winrm_password: ${{ env.winrm_password }}
  


 