name: Build Windows 2022 with Packer
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: "self-hosted"  # (optional) name of the runner labels, groups
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Load Connect credentials
        uses: 1password/load-secrets-action@v1
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Run script file
        run: |
          chmod +x ./ScriptsMain/win2022.sh
          ./ScriptsMain/win2022.sh
        shell: bash
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

         
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: latest
  
      - name: Run `packer init`
        id: init
        run: "packer init ./build.pkr.hcl"
  
      - name: Run `packer validate`
        id: validate
        run: "packer validate ./build.pkr.hcl"
  


 